### ISSUE TITLE
Compilation aborting

### ISSUE THREAD

**Issue by yurimotilev** [castle-engine/castle-game#1]
Error: Can't open resource file "C:\Users\yurimotylev\Desktop\tmp\castle-game-master\automatic-windows-resources.res"

Castle Game Engine version: 7.0-alpha.snapshot (unstable) (commit 431215ff3ff1312fe3fd25899c35fc90c32bb80e).
Editor compiled with FPC 3.2.2.
Editor platform: Desktop, OS: Win64, CPU: x86_64 (this exe is using 64-bit architecture).

Compilation OK if I manually rename castle-auto-generated-resources.res to automatic-windows-resources.res

**Comment by michaliskambi** [comment]
Fixed, thanks. 

We indeed removed the old name `automatic-windows-resources.res` from CGE recently, it was deprecated for a long time.
